DllExport void curveinit();
DllExport DBL curvedegree1get();
DllExport BOOL curvedivragchk(DBL rag1, DBL rag2);
DllExport void curveroundtrns(DBL srcx, DBL srcy, DBL x0, DBL y0, DBL rag, DBL *dstx, DBL *dsty);
DBL curve2divcrnr(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3);
DBL curvevertical(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3);
int curvenoragchk(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3, DBL *rag);
DBL curveraglegalhpai(DBL rag);
DllExport DBL curveraglegal(DBL rag);
DllExport int curve3pcenterget(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3, DBL FAR *x0, DBL FAR *y0);
int curvenocrosschk(DBL rag1, DBL rag2);
int curvetanerrchk(DBL rag);
int curveroundchk(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3, DBL x0, DBL y0);
DllExport int curve3pragrget(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3, DBL x0, DBL y0, DBL FAR *rag01, DBL FAR *rag03, DBL FAR *r);
DllExport int curveragnoget(DBL rag);
DllExport int curveragrget(DBL x1, DBL y1, DBL x2, DBL y2, DBL x0, DBL y0, DBL *rag01, DBL *rag02, DBL *r);
DllExport int curvecenterget(DBL rag1, DBL x1, DBL y1, DBL x2, DBL y2, DBL *x0, DBL *y0);
DllExport int curvedivpointget(DBL rag1, DBL x1, DBL y1, DBL x2, DBL y2, DBL rag2, DBL *x12, DBL *y12);
DllExport void curvebezecontrolpointget(DBL x1, DBL y1, DBL x2, DBL y2, DBL rag, DBL *xp, DBL *yp);
DllExport void curvenoragtocurverag(DBL *rag1, DBL *rag2);
int curvebezelinechk(dbezetype beze, DBL limit);
void curvebezedivbeze(dbezetype *sbeze, dbezetype *d1beze, dbezetype *d2beze);
int curvelimitareachk(DBL x1, DBL y1, DBL x2, DBL y2, DBL limit, DBL tx, DBL ty);
DllExport int curveperpendicular(DBL sx, DBL sy, DBL ex, DBL ey, DBL x, DBL y, DBL *cx, DBL *cy);
DllExport int curveonlinechk(DBL x1, DBL y1, DBL x2, DBL y2, DBL x, DBL y);
DllExport void curve3pragget(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3, DBL x0, DBL y0, DBL *r1, DBL *r12, DBL *r23, DBL *r3);
DllExport void curvebezettdivget(dbezetype sbz, DBL st, DBL et, dbezetype *dbz);
DllExport void curveonpointtocntrlpoint(dbezetype *dbz, DBL tp1, DBL tp2);
int curvesmltqu(DBL a, DBL b, DBL c, DBL d, DBL e, DBL f, DBL *x, DBL *y);
DllExport void curvebezetpointget(dbezetype bz, DBL t, DBL *x, DBL *y);
DllExport void curvesymxytrns(DBL a, DBL b, DBL t1, DBL t2, DBL *x, DBL *y);
DllExport int curvenkindget(DBL x1, DBL y1, DBL x2, DBL y2, DBL x3, DBL y3);
DllExport int curvecrosslineinareachk(dlinetype line1, dlinetype line2);
DllExport int curvecrosslnlnxyget(dlinetype line1, dlinetype line2, DBL *x, DBL *y);
DllExport int curvecrosslinelinexyget(dlinetype line1, dlinetype line2, DBL *x, DBL *y);
DllExport void curvecrosslinekdget(DBL x1,DBL y1,DBL x2,DBL y2,DBL *k,DBL *d);
DllExport void curvecrosspointxyget(DBL k1, DBL d1, DBL k2, DBL d2, DBL *x, DBL *y);
DllExport int curvecrossonlinechk(dlinetype line, DBL x, DBL y);
DllExport void cruvearctobeze(darctype arc,  dbezetype *bz);
DllExport DBL curvegetlength(DBL x1, DBL y1, DBL x2, DBL y2);
