DllExport void mojienvinit();
DllExport void mojienvend();
DllExport void mojienvsetmaxlegal(int flag);
DllExport int mojienvcheckmaxlegal();
DllExport void mojienvsetbold(int flag);
DllExport int mojienvcheckbold();
DllExport void mojienvsetitric(int flag);
DllExport int mojienvcheckitric();
DllExport void mojienvsetunderl(int flag);
DllExport int mojienvcheckunderl();
DllExport void mojienvsettrnslimit(DBL dlimit);
DllExport void mojienvgettrnslimit(LPDBL dlimit);
DllExport void mojienvsetstring(LPTSTR instr);
DllExport void mojienvgetstring(LPTSTR instr);
DllExport void mojienvgetfontpath(LPTSTR fontpath);
DllExport void mojienvsetfontpath(LPTSTR fontpath);
DllExport void mojienvgetfontname(LPTSTR fontname);
DllExport void mojienvsetfontname(LPTSTR fontname);
DllExport void mojienvgetesseisuno(LPINT no);
DllExport void mojienvsetesseisuno(int no);
DllExport void mojienvgetarceisuno(LPINT no);
DllExport void mojienvsetarceisuno(int no);
DllExport void mojienvgettategakiflag(LPINT tateflg);
DllExport void mojienvsettategakiflag(int tateflg);
DllExport void mojienvgetspacekind(LPINT spkflg);
DllExport void mojienvsetspacekind(int spkflg);
DllExport void mojienvgetyokomojiflag(LPINT yokomoji);
DllExport void mojienvsetyokomojiflag(int yokomoji);
DllExport void mojienvgetstart(LPDBL dstartx, LPDBL dstarty);
DllExport void mojienvsetstart(DBL dstartx, DBL dstarty);
DllExport void mojienvgetsize(LPDBL dfwidth, LPDBL dfhight);
DllExport void mojienvsetsize(DBL dfwidth, DBL dfhight);
DllExport void mojienvgetspace(LPDBL dmojispace, LPDBL dlinespace);
DllExport void mojienvsetspace(DBL dmojispace, DBL dlinespace);
DllExport void mojienvgetstrlen(LPDBL dstringlen);
DllExport void mojienvsetstrlen(DBL dstringlen);
DllExport void mojienvsetstartkind(int nkind);
DllExport void mojienvgetstartkind(LPINT nkind);
DllExport void mojienvsetconerkind(int nkind);
DllExport void mojienvgetconerkind(LPINT nkind);
DllExport void mojienvsetmojicount(DBL dmjcnt);
DllExport void mojienvgetmojicount(LPDBL dmjcnt);
DllExport void mojienvsetgyakukind(int nkind);
DllExport void mojienvgetgyakukind(LPINT nkind);
DllExport void mojienvsetsmpltext(LPTSTR smpl);
DllExport void mojienvgetsmpltext(LPTSTR smpl);
DllExport void mojienvsetarngkind(int nkind);
DllExport void mojienvgetarngkind(LPINT nkind);
DllExport void mojienvsetorder(int nkind);
DllExport void mojienvgetorder(LPINT nkind);
DllExport void mojienvsetstrgslop(DBL dslop);
DllExport void mojienvgetstrgslop(LPDBL dslop);
DllExport void mojienvsetmojiround(DBL dround);
DllExport void mojienvgetmojiround(LPDBL dround);
DllExport void mojienvflistinit();
DllExport void mojienvflistopen(LPTSTR lpMode);
DllExport void mojienvflistclose();
DllExport int mojienvgetflistmax();
DllExport void mojienvsetflist(int type, LPTSTR sfname, LPTSTR ffname);
DllExport void mojienvgetflist(int idx, int *type, LPTSTR sfname, LPTSTR ffname);
DllExport void mojienvgetfonttypename(LPTSTR fontname, LPINT retftype, LPTSTR fontfullname);
DllExport int mojienvgetfontno(LPTSTR fontname);
DllExport int mojienvgetfonttype(LPTSTR fullname);
DllExport void mojienvgetfilename(LPTSTR fontname, LPTSTR filename);
DllExport void mojienvgetsfilename(LPTSTR fontname, LPTSTR filename);
