DllExport void plotpentblset(int idx, int val);
DllExport void plotprebufset(LPSTR buf);
DllExport void plotpostbufset(LPSTR buf);
void plotfilenameset(LPSTR filename);
void plotdatanameset(LPSTR dataname);
void plotsetparaminit(DBL plstep, DBL rlstep, DBL smm, DBL emm);
void plotgetparaminit(LPDBL plstep, LPDBL rlstep, LPDBL smm, LPDBL emm);
void plotkindset(int kind);
void plotmmsizeset(DBL xsize, DBL ysize);
void plotstepset(DBL step);
void plotmmstartset(DBL sx, DBL sy);
void plotmmstartget(DBL *sx, DBL *sy);
void plotmmcntrset(DBL cx, DBL cy);
void plottimeset(DBL xtime, DBL ytime);
void plotcntrkindset(int cntrkind);
DllExport void plotmovexyset(DBL xmove, DBL ymove);
void plotcomidset(int id);
DllExport void plotgetcrtxy(LPDBL crtx, LPDBL crty);
DllExport void plotmmareaset(DBL sx, DBL sy, DBL ex, DBL ey);
DllExport void plotdxymmtostep(LPDBL x, LPDBL y);
DllExport void plotdxysteptomm(LPDBL x, LPDBL y);
DllExport void plotlenmmtostep(LPDBL len);
void plotstartendmmget(DBL *smm, DBL *emm);
void plotsmmlegalset(DBL smm);
int plotemmeffectchk();
void plotemmlegalset(DBL emm);
void plotsxchanelslct(int num);
int plotpausesend();
void plotabsxyget(DBL *plotx, DBL *ploty);
void plotmmxyget(DBL *mmx, DBL *mmy);
void plotmmlenget(DBL *len);
void plotabstimetrns(DBL *x, DBL *y);
int plotenkolimitchk(DBL x0, DBL y0, DBL r);
void plotoutlength(DBL xlength, DBL ylength);
void plotdrawinit();
void plotdrawend();
void plotpaintinit();
void plotpenoutinit(int penno);
void plotpaintend();
void plotpenoutend();
void plotplotinit();
void plotplotend();
void plotdynapaintmodeset(int mode);
void plotdynaclrnoset(int clrno);
void plotdynafillstart();
void plotdynafillend();
void plotdynarulestart();
void plotdynaruleend();
void plotdynathickout(DBL thick);
void plotoutblockstart();
void plotoutblockend();
void plotoutrejionstart();
void plotoutrejionend();
void plotoutplgnend();
void plotmovekind(int kind, DBL movex, DBL movey);
void plotdrawst();
void plotmove(DBL movex, DBL movey);
void plotrejionlastjoin();
void plotdrawline(DBL x1, DBL y1, DBL x2, DBL y2);
void plotdrawenko(DBL x0, DBL y0, DBL r, DBL rag1, DBL rag2, DBL sx, DBL sy, DBL ex, DBL ey);
void plotdraw3penko(DBL x1, DBL y1, DBL x12, DBL y12, DBL x2, DBL y2);
void plotdraw3paenko(int round, DBL x1, DBL y1, DBL x3, DBL y3, DBL r, DBL x0, DBL y0);
void plotdraw3pmenko(int round, DBL x1, DBL y1, DBL x2, DBL y2, DBL x0, DBL y0);
void plotendhome();
void plotpenup(DBL x, DBL y);
void plotlipsnumtostrg(DBL dnum, char txt[]);
void plotoutstring(LPSTR  buf);
