#define	EDITSTYLE		WS_VISIBLE|WS_TABSTOP|WS_BORDER|WS_CHILD|ES_AUTOHSCROLL
#define	EDITNONSTYLE		WS_VISIBLE|WS_TABSTOP|WS_BORDER|WS_CHILD|ES_AUTOHSCROLL|ES_READONLY
#define EDITMLTSTYLE	EDITSTYLE|ES_MULTILINE|ES_AUTOVSCROLL|ES_WANTRETURN
#define SPINSTYLE		WS_VISIBLE|UDS_SETBUDDYINT|UDS_ALIGNRIGHT|UDS_AUTOBUDDY|UDS_ARROWKEYS|UDS_NOTHOUSANDS
//#define SPINSTYLE       WS_VISIBLE|UDS_ALIGNRIGHT|UDS_AUTOBUDDY|UDS_ARROWKEYS
#define	COMBOSTYLE		WS_VISIBLE|WS_TABSTOP|WS_VSCROLL|CBS_DROPDOWN|CBS_AUTOHSCROLL|CBS_HASSTRINGS
#define	COMBONOSSTYLE	WS_VISIBLE|WS_TABSTOP|WS_VSCROLL|CBS_DROPDOWN|CBS_HASSTRINGS
#define TOOLBARSTYLE	WS_CHILD|WS_VISIBLE|CBRS_TOP|CBRS_TOOLTIPS|CBRS_FLYBY|CBRS_HIDE_INPLACE|CBRS_SIZE_DYNAMIC
//#define TOOLBARSTYLE	WS_CHILD|WS_VISIBLE|CBRS_TOP|CBRS_TOOLTIPS|CBRS_FLYBY|CBRS_SIZE_DYNAMIC
#define SHEETSTYLE		DS_MODALFRAME|DS_3DLOOK|DS_CONTEXTHELP|DS_SETFONT|WS_POPUP|WS_CAPTION
#define BTNSTYLE		BS_PUSHBUTTON|WS_VISIBLE|WS_TABSTOP|WS_CHILD
#define CKBTNSTYLE		BS_AUTOCHECKBOX|WS_VISIBLE|WS_TABSTOP
#define	STATICSTYLE		WS_CHILD|WS_VISIBLE
#define	SEPARATORDOT	8

#define	NOOP			0
#define	SETFOCUSEVENT	1
#define	KILLFOCUSEVENT	2
#define	INITEVENT		10
#define	SETEVENT		11
#define	RESETEVENT		12
#define	MOVEEVENT		13
#define	REDRAWEVENT		14
#define	KEYINEVENT		15
#define	ENDEVENT		16
#define	DRAWEVENT		17
#define UPMOVEEVENT		18
#define	SETEVENT2		19
#define	DLGSETEVENT		21
#define	DLGRESETEVENT	22
#define	DLGENDEVENT		23
#define	DLGDRAWEVENT	24
#define	WINSETEVENT		31
#define	WINRESETEVENT	32
#define TIMEREVENT		33
#define	DBLSETEVENT		41
#define	DBLRESETEVENT	42
#define	USER1EVENT		51
#define	USER2EVENT		52
#define	USER3EVENT		53
#define	USER4EVENT		54
#define	USER5EVENT		55
#define	USER6EVENT		56
#define	USER7EVENT		57
#define	USER8EVENT		58
#define	USER9EVENT		59
#define	USER10EVENT		60
#define	USER11EVENT		61
#define	USER12EVENT		62
#define	USER13EVENT		63
#define	USER14EVENT		64
#define	USER15EVENT		65
#define	USER16EVENT		66
#define	USER17EVENT		67
#define	USER18EVENT		68
#define	USER19EVENT		69
#define	USER20EVENT		70
#define	CMDPEVENT		71

#define	WM_REDROW	WM_USER + 101
#define	WM_DLGSET	WM_USER + 102
#define	WM_DLGRESET	WM_USER + 103
#define	WM_WINSET	WM_USER + 104
#define	WM_WINRESET	WM_USER + 105
#define	WM_DRAW		WM_USER + 106
#define	WM_FRCHNGFOCUS	WM_USER + 111
#define	WM_BKCHNGFOCUS	WM_USER + 112
#define	WM_FRCHNGPAGE	WM_USER + 113
#define	WM_BKCHNGPAGE	WM_USER + 114
#define	WM_CHILDEND		WM_USER + 115
#define	WM_CRFRCHNGFOCUS	WM_USER + 120
#define	WM_USER1SET	WM_USER + 131
#define	WM_USER2SET	WM_USER + 132
#define	WM_USER3SET	WM_USER + 133
#define	WM_USER4SET	WM_USER + 134
#define	WM_USER5SET	WM_USER + 135
#define	WM_USER6SET	WM_USER + 136
#define	WM_USER7SET	WM_USER + 137
#define	WM_USER8SET	WM_USER + 138
#define	WM_USER9SET	WM_USER + 139
#define	WM_USER10SET	WM_USER + 140
#define	WM_USER11SET	WM_USER + 141
#define	WM_USER12SET	WM_USER + 142
#define	WM_USER13SET	WM_USER + 143
#define	WM_USER14SET	WM_USER + 144
#define	WM_USER15SET	WM_USER + 145
#define	WM_USER16SET	WM_USER + 146
#define	WM_USER17SET	WM_USER + 147
#define	WM_USER18SET	WM_USER + 148
#define	WM_USER19SET	WM_USER + 149
#define	WM_USER20SET	WM_USER + 150
#define WM_XFERDONE	(WM_USER+201)

#define	CUSKIND_APPSTARTING		0 //標準矢印カーソルおよび小型砂時計カーソル
#define	CUSKIND_ARROW			1 //標準矢印カーソル
#define	CUSKIND_CROSS			2 //十字カーソル 
#define	CUSKIND_IBEAM			3 //アイビーム (縦線) カーソル 
#define	CUSKIND_ICON			4 //現在は使われません 
#define	CUSKIND_NO				5 //禁止カーソル 
#define	CUSKIND_SIZE			6 //現在は使われません 
#define	CUSKIND_SIZEALL			7 //4 方向矢印カーソル 
#define	CUSKIND_SIZENESW		8 //斜め左下がりの両方向矢印カーソル 
#define	CUSKIND_SIZENS			9 //上下両方向矢印カーソル 
#define	CUSKIND_SIZENWSE		10 //斜め右下がりの両方向矢印カーソル 
#define	CUSKIND_SIZEWE			11 //左右両方向矢印カーソル 
#define	CUSKIND_UPARROW			12 //垂直の矢印カーソル 
#define	CUSKIND_WAIT			13 //砂時計カーソル 
#define CUSKIND_HANDGOO			19 //手のマーク
#define CUSKIND_HAND			20 //手のマーク
#define CUSKIND_ZOOMIN			21 //手のマーク
#define CUSKIND_ZOOMOUT			22 //手のマーク
#define	CUSKIND_ARROWPLUS		23 //標準矢印＋点
#define CUSKIND_NON				99
