//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Ses.rc で使用されます
//
#define IDC_BTNOPTION                   3
#define IDC_DELETE                      3
#define IDCANCEL2                       3
#define IDR_SGSTYPE_SRVR_IP             4
#define IDR_SESTYPE_SRVR_IP             4
#define IDR_SGSTYPE_SRVR_EMB            5
#define IDR_SESTYPE_SRVR_EMB            5
#define IDR_SGSTYPE_CNTR_IP             6
#define IDR_SESTYPE_CNTR_IP             6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDR_MAINFRAME                   111
#define IDR_SGSTYPE                     112
#define IDR_SESTYPE                     113
#define IDR_SGSTYPE1                    114
#define IDR_SESTYPE1                    115
#define IDR_ASSIST                      116
#define IDR_LEFTSIDE                    117
#define IDR_POPUPMENU                   118
#define IDR_SGSTYPE2                    119
#define IDR_CDRNTTOOLBAR                121
#define IDR_LINETOOLBAR                 122
#define IDR_OBJTOOLBAR                  123
#define IDR_OBJTOOLBAR1                 124
#define IDR_POINTTOOLBAR                125
#define IDC_CUS_HAND                    131
#define IDC_CUS_ZOOMIN                  132
#define IDC_CUS_ZOOMOUT                 133
#define IDC_CUS_ARROWPLUS               134
#define IDB_WAKUTOOLBAR                 155
#define IDB_PREBTN                      161
#define IDB_NEXTBTN                     162
#define IDB_GRAPTN1                     163
#define IDB_GRAPTN2                     164
#define IDB_GRAPTN3                     165
#define IDB_GRAPTN4                     166
#define IDB_GRAPTN5                     167
#define IDB_GRABTN                      168
#define IDB_SIZEBIG1                    171
#define IDB_SIZEBIG2                    172
#define IDB_SIZEBIG3                    173
#define IDB_SIZESMALL1                  181
#define IDB_SIZESMALL2                  182
#define IDB_SIZESMALL3                  183
#define IDB_MOVELEFT1                   191
#define IDB_MOVELEFT2                   192
#define IDB_MOVELEFT3                   193
#define IDB_MOVERIGHT1                  194
#define IDB_MOVERIGHT2                  195
#define IDB_MOVERIGHT3                  196
#define IDB_MOVEUP1                     197
#define IDB_MOVEUP2                     198
#define IDB_MOVEUP3                     199
#define IDB_MOVEDOWN1                   214
#define IDB_MOVEDOWN2                   215
#define IDB_MOVEDOWN3                   216
#define IDB_NONCLRBTN                   217
#define IDB_PREBTN1                     218
#define IDB_STRGVSTRCTS2                220
#define IDB_STRGVSTRCTS3                221
#define IDB_STRGVSTRCTS1                229
#define IDB_BITMAP1                     231
#define IDB_BITMAP2                     232
#define IDB_BITMAP3                     233
#define IDB_BITMAP4                     234
#define IDB_BITMAP5                     235
#define IDB_BITMAP6                     236
#define IDB_BITMAP7                     237
#define IDB_BITMAP8                     238
#define IDB_BITMAP9                     239
#define IDB_BITMAP10                    240
#define IDB_BITMAP11                    241
#define IDB_STRGTATE                    245
#define IDB_STRGTYNON                   246
#define IDB_STRGYOKO                    247
#define IDB_STARTLB                     251
#define IDB_STARTLT                     252
#define IDB_STARTRT                     253
#define IDB_STARTRB                     254
#define IDB_STARTCT                     255
#define IDB_CONERLB                     261
#define IDB_CONERLT                     262
#define IDB_CONERRT                     263
#define IDB_CONERRB                     264
#define IDB_CONERCT                     265
#define IDB_SIZERLBIG1                  271
#define IDB_SIZERLBIG2                  272
#define IDB_SIZERLBIG3                  273
#define IDB_SIZEUDBIG1                  275
#define IDB_SIZEUDBIG2                  276
#define IDB_SIZEUDBIG3                  277
#define IDB_SIZEUDSMALL1                281
#define IDB_SIZEUDSMALL2                282
#define IDB_SIZEUDSMALL3                283
#define IDB_SIZERLSMALL1                285
#define IDB_SIZERLSMALL2                286
#define IDB_SIZERLSMALL3                287
#define IDB_ORIGHTUP                    295
#define IDB_OLEFTDOWN                   297
#define IDB_OLEFTUP                     298
#define IDB_ORIGHTDOWN                  299
#define IDD_MOJILOAD                    311
#define IDD_MOJISAVE                    312
#define IDD_DIALOG1                     313
#define IDD_PART_LOAD                   314
#define IDD_PART_SAVE                   315
#define IDD_SIZE_BOXS                   316
#define IDD_SCRNCLRSET                  317
#define IDD_RULESTYLE                   318
#define IDD_WAKUADDATR                  319
#define IDD_PROTECT                     321
#define IDD_STRG_VSTRUCT                322
#define IDD_SCRNENV                     323
#define IDD_WAKU_GRUP                   324
#define IDD_WAKU_PAPER                  325
#define IDD_WAKU_INPUT                  326
#define IDD_WAKU_SAVE                   328
#define IDD_WAKU_LOAD                   329
#define IDD_WAKU_DELETE                 331
#define IDD_WAKU_LINEUP                 332
#define IDD_KAMON_LOAD                  333
#define IDD_OUTLINE                     334
#define IDD_TTTEXT                      335
#define IDD_EDITBAR                     336
#define IDD_CLRTOOLBAR                  337
#define IDD_CLRBAR                      338
#define IDD_DIRSLCT                     339
#define IDD_STRG_INPUT                  341
#define IDD_SHADOW                      342
#define IDD_TRACE_IMAGE                 343
#define IDD_GRADATION                   344
#define IDD_INNUM                       345
#define IDD_CONER_KIND                  346
#define IDD_2POINTSIZETRNS              347
#define IDD_TEXTINPUT                   348
#define IDD_STRG_LINEUP                 349
#define IDD_STRG_INSEART                351
#define IDD_MOJI_SIZE                   352
#define IDD_MOJI_MOVE                   353
#define IDD_MSURATRSET                  354
#define IDD_SIZE_CRCL                   355
#define IDD_PLOTOUT                     356
#define IDD_WAKUBARG                    357
#define IDD_WAKU_EDIT                   358
#define IDD_BMP_ROUND                   359
#define IDD_WAKUADDATR1                 361
#define IDD_WAKUBAR1                    362
#define IDD_WAKUBAR2                    363
#define IDD_WAKUBAR3                    364
#define IDD_WAKUBAR4                    365
#define IDD_SIZE_LIST                   366
#define IDD_WAKU_SORT                   367
#define IDD_FONTCHNG                    368
#define IDD_DIVPLOTER                   369
#define IDD_INNUMPAIR                   371
#define IDD_ESKMN_LOAD                  372
#define IDD_ESKMN_SAVE                  373
#define IDD_SCRNCLRSET1                 374
#define IDD_WAKU_PAPERDEL               375
#define IDD_IMAGESAVE                   376
#define IDD_WAKUATRCHANGE               377
#define IDD_GAIJI                       378
#define IDD_CRCTLOAD                    379
#define IDD_CRCTDISP                    380
#define IDD_DBEDIT                      381
#define IDD_MOJI_FITING                 382
#define IDD_ESKAMON                     383
#define IDD_FILELOAD                    384
#define IDD_FILESAVE                    385
#define IDD_EPSKAMON_LOAD               386
#define IDD_WAKU_EDIY                   387
#define IDD_VIEW_FILE                   388
#define IDD_WAKU_PAPERADD               390
#define IDD_WAKUBARG1                   391
#define IDD_WAKUBARG2                   392
#define IDD_GAIJI_SAVE                  393
#define IDD_GAIJI_LOAD                  394
#define IDD_GAIJI_SLCT                  395
#define IDD_SLCTSTRG                    396
#define IDD_CPTR_FOLDER                 397
#define IDD_MDBSLCT                     398
#define IDD_SETPROTECT                  399
#define IDD_SETMACKEY                   400
#define IDD_SETSPACE                    411
#define IDD_STRG_ARC                    412
#define IDD_WAKU_CPTR                   413
#define IDD_WAKUSIDE                    414
#define IDD_XLSSLCT                     415
#define IDD_PROGBAR                     421
#define IDD_SLCTADRS                    422
#define IDD_SLCTFTPADRS                 423
#define IDD_MEMOENVSET                  424
#define IDD_WAKU_INSEKIJI               425
#define IDC_COMBO1                      1000
#define IDC_EDINPUT                     1001
#define IDC_STRGVSTRCT1                 1002
#define IDC_WORKXSIZE                   1003
#define IDC_NEXTPAGE                    1004
#define IDC_PAPERPATH                   1005
#define IDC_EDCHKKEY                    1009
#define IDC_STRGVSTRCT2                 1011
#define IDC_WORKYSIZE                   1012
#define IDC_EDXSIZE                     1013
#define IDC_EDYSIZE                     1014
#define IDC_MATCHING                    1015
#define IDC_CMBPAPERSIZE                1016
#define IDC_EDPLTXSIZE                  1021
#define IDC_CMBPAPER                    1022
#define IDC_CMBPAPERNAME                1023
#define IDC_BEFORPAGE                   1024
#define IDC_PAPERSIZEX                  1025
#define IDC_STRGVSTRCT3                 1026
#define IDC_PLOTSIZE                    1031
#define IDC_SRCHSTRG                    1032
#define IDC_EDLENGTH                    1033
#define IDC_CMBFONT                     1034
#define IDC_EDPLTYSIZE                  1035
#define IDC_PARTPATH                    1041
#define IDC_EDSLCTFILE                  1042
#define IDC_PAPERSIZEY                  1043
#define IDC_CHK_EQUAL                   1044
#define IDC_KMNVIEW                     1045
#define IDC_PAPERSX                     1051
#define IDC_RESET                       1052
#define IDC_PLOTXSIZE                   1053
#define IDC_SPPLGNCOUNT                 1054
#define IDC_PAPERSY                     1055
#define IDC_CHK_NOROUND                 1061
#define IDC_PLOTYSIZE                   1062
#define IDC_SPFLATPAR                   1063
#define IDC_DLGSET                      1064
#define IDC_PAPERWIDTH                  1065
#define IDC_EDSTRG                      1071
#define IDC_PLOTSX                      1072
#define IDC_SPSTRGSIZE                  1073
#define IDC_PAPERHIGHT                  1074
#define IDC_PLOTSY                      1075
#define IDC_EDMOJICOUNT                 1081
#define IDC_EDSTEP                      1082
#define IDC_CHKTATEGAKI                 1083
#define IDC_PLOTSTEP                    1084
#define IDC_SPMOJICOUNT                 1085
#define IDC_PAPERNAME                   1091
#define IDC_AREA                        1092
#define IDC_CNTRKIND                    1093
#define IDC_RDOCODESORT                 1094
#define IDC_CMBUNIT                     1095
#define IDC_PORTNAME                    1111
#define IDC_RDOBUSYUSORT                1112
#define IDC_BUTTON1                     1113
#define IDC_PLOTNAME                    1114
#define IDC_BTN_CLRCHANGE               1115
#define IDC_RDOKAKUSUSORT               1116
#define IDC_DATAPATH                    1117
#define IDC_BTN_SMALL                   1118
#define stc32                           0x045f
#define IDC_WAKUPATH                    1119
#define IDC_BTN_RLBIG                   1120
#define IDC_FONTPATH                    1121
#define IDC_BTN_RLSMALL                 1122
#define IDC_KMONPATH                    1123
#define IDC_BTN_UDBIG                   1124
#define IDC_OUTDPATH                    1125
#define IDC_BTN_UDSMALL                 1126
#define IDC_TBMPPATH                    1127
#define IDC_BTN_LEFTMOVE                1128
#define IDC_TEMPPATH                    1129
#define IDC_INSTRG                      1130
#define IDC_BTN_RIGHTMOVE               1131
#define IDC_FIXFLAG                     1132
#define IDC_BTN_UPMOVE                  1133
#define IDC_BTN_DOWNMOVE                1134
#define IDC_TRNS                        1135
#define IDC_MODE1                       1141
#define IDC_MODE2                       1142
#define IDC_MODE3                       1143
#define IDC_MODE4                       1144
#define IDC_MODE5                       1145
#define IDC_MODE6                       1146
#define IDC_MODE7                       1147
#define IDC_MODE8                       1148
#define IDC_MODE9                       1149
#define IDC_MODE10                      1150
#define IDC_MODE11                      1151
#define IDC_WKGRUPNAME                  1161
#define IDC_DISP                        1162
#define IDC_CREATE                      1163
#define IDC_EDITSTRG                    1164
#define IDC_CRCT                        1165
#define IDC_CRCTLOAD                    1166
#define IDC_CANCEL                      1167
#define IDC_CRCTDISP                    1167
#define IDC_OUT                         1168
#define IDC_CRCTSAVE                    1169
#define IDC_LOAD                        1171
#define IDC_INPEND                      1172
#define IDC_EXIT                        1173
#define IDC_EDSTARTX                    1174
#define IDC_SPSTARTX                    1175
#define IDC_SPKMNSIZE                   1176
#define IDC_GAIJI                       1177
#define IDC_EDSTARTY                    1178
#define IDC_NEXT                        1178
#define IDC_NAMELIST                    1179
#define IDC_PREV                        1179
#define IDC_SPSTARTY                    1181
#define IDC_KMNSIZE                     1182
#define IDC_EDWIDTH                     1183
#define IDC_SRCHCHAR                    1184
#define IDC_SPWIDTH                     1185
#define IDC_EDHIGHT                     1186
#define IDC_SPHIGHT                     1187
#define IDC_EDMOJISPACE                 1188
#define IDC_BTN_PART                    1189
#define IDC_SPMOJISPACE                 1191
#define IDC_EDSTRGSPACE                 1192
#define IDC_SPSTRGSPACE                 1193
#define IDC_EDSTRGLEN                   1194
#define IDC_SPSTRGLEN                   1195
#define IDC_EDSTRGSLOP                  1196
#define IDC_SPSTRGSLOP                  1197
#define IDC_SPTRNSLIMIT                 1198
#define IDC_EDSMPLTEXT                  1199
#define IDC_CBSTRGORDER                 1211
#define IDC_CBFONTNAME                  1212
#define IDC_CKTATEGAKI                  1213
#define IDC_CKGYAKU                     1214
#define IDC_CKMOJIDATA                  1215
#define IDC_CBSHADOWKIND                1216
#define IDC_EDDISTANCE                  1217
#define IDC_CBCONER_KIND                1218
#define IDC_SPDISTANCE                  1219
#define IDC_PLTCOMBO                    1221
#define IDC_SPROUNDRAG                  1222
#define IDC_EDROUNDRAG                  1223
#define IDC_SPTHICK                     1224
#define IDC_PREBTN                      1225
#define IDC_NEXTBTN                     1226
#define IDC_NONCLRBTN                   1227
#define IDC_THICK                       1228
#define IDC_CHECK_INSMODE               1229
#define IDC_STATIC1                     1251
#define IDC_STATIC2                     1252
#define IDC_STATIC3                     1253
#define IDC_STATIC4                     1254
#define IDC_STATIC5                     1255
#define IDC_STATIC6                     1256
#define IDC_STATIC7                     1257
#define IDC_STATIC8                     1258
#define IDC_STATIC9                     1259
#define IDC_STATIC10                    1260
#define IDC_CHKKTGK1                    1271
#define IDC_CHKKTGK2                    1272
#define IDC_CHKKTGK3                    1273
#define IDC_CHKKTGK4                    1274
#define IDC_CHKKTGK5                    1275
#define IDC_CHKKTGK6                    1276
#define IDC_CHKKTGK7                    1277
#define IDC_CHKKTGK8                    1278
#define IDC_CHKKTGK9                    1279
#define IDC_CHKKTGK10                   1280
#define IDC_EDIT1                       1311
#define IDC_EDIT2                       1312
#define IDC_EDIT3                       1313
#define IDC_EDIT4                       1314
#define IDC_EDIT5                       1315
#define IDC_EDIT6                       1316
#define IDC_EDIT7                       1317
#define IDC_EDIT8                       1318
#define IDC_EDIT9                       1319
#define IDC_EDIT10                      1320
#define IDC_EDIT11                      1321
#define IDC_EDIT12                      1322
#define IDC_EDIT13                      1323
#define IDC_EDIT14                      1324
#define IDC_EDIT15                      1325
#define IDC_EDIT16                      1326
#define IDC_EDIT17                      1327
#define IDC_EDIT18                      1328
#define IDC_EDIT19                      1329
#define IDC_EDIT20                      1330
#define IDC_EDIT21                      1331
#define IDC_EDIT22                      1332
#define IDC_EDIT23                      1333
#define IDC_EDIT24                      1334
#define IDC_EDIT25                      1335
#define IDC_EDIT26                      1336
#define IDC_EDIT27                      1337
#define IDC_EDIT28                      1338
#define IDC_EDIT29                      1339
#define IDC_EDIT30                      1340
#define IDC_DIRLIST                     1371
#define IDC_STSLCTNAME                  1372
#define IDC_STIMAGE                     1373
#define IDC_BTN_DATA                    1374
#define IDC_BTN_FONT                    1375
#define IDC_BTN_OUT                     1381
#define IDC_BTN_TEMP                    1382
#define IDC_BTN_WAKU                    1383
#define IDC_BTN_KMN                     1384
#define IDC_BTN_BTMP                    1385
#define IDC_STSMPLE                     1391
#define IDC_STTOP                       1392
#define IDC_STSAMPLE_CLR                1393
#define IDC_STAREA_TOP                  1394
#define IDC_STIMAGE_AREA                1395
#define IDC_SLIDER1                     1411
#define IDC_LINE_TRACE                  1412
#define IDC_BTN_SIZEBIG                 1413
#define IDC_STTITLE                     1414
#define IDC_BTN_SIZESMALL               1415
#define IDC_BTN_MOVEUP                  1421
#define IDC_BTN_MOVEDOWN                1422
#define IDC_EDNUM                       1423
#define IDC_EDNUMY                      1425
#define IDC_STTITLEY                    1431
#define IDC_STUNITY                     1432
#define IDC_ED_INSSTRG                  1433
#define IDC_ED_STEP                     1434
#define IDC_BTN_MOVERIGHT               1435
#define IDC_EDQUALITY                   1441
#define IDC_BTN_MOVELEFT                1442
#define IDC_STUNIT                      1443
#define IDC_STUNIT2                     1444
#define IDC_STUNIT3                     1445
#define IDC_SPFONTSIZE                  1451
#define IDC_SPFONTSIZE2                 1452
#define IDC_SPFONTSIZE3                 1453
#define IDC_PLOTOUT                     1454
#define IDC_EDCX                        1455
#define IDC_EDSUBKEY                    1457
#define IDC_SPCX                        1461
#define IDC_EDCY                        1462
#define IDC_MSUR_STRG                   1463
#define IDC_SPCY                        1464
#define IDC_MSUR_FONTSIZE               1465
#define IDC_BTNGRUPSAVE                 1471
#define IDC_CHK_HORS                    1472
#define IDC_CHK_LORC                    1473
#define IDC_DLGRESET                    1474
#define IDC_CHK_OORN                    1475
#define IDC_CBKIND                      1481
#define IDC_SPNXSIZE                    1482
#define IDC_BTNPRINT                    1483
#define IDC_SPNYSIZE                    1484
#define IDC_BTNTATEGAKI                 1485
#define IDC_SPNQUALITY                  1491
#define IDC_EDTEXT                      1492
#define IDC_EDWORKYSIZE                 1493
#define IDC_EDWORKXSIZE                 1494
#define IDC_BTNPAPERSAVE                1495
#define IDC_CMBPLOTER                   1511
#define IDC_CMBGRUP                     1512
#define IDC_SAVE                        1513
#define IDC_BTNSET                      1514
#define IDC_BTNRESET                    1515
#define IDC_BTNDEF                      1521
#define IDC_PATH                        1522
#define IDC_EDKMNSIZE                   1523
#define IDC_PAPERSIZE                   1524
#define IDC_STCRCTCNT                   1525
#define IDC_LST_CRCT                    1531
#define IDC_CHKFIXED                    1532
#define IDC_CHKYOKOMOJI                 1533
#define IDC_SPNORISIRO                  1534
#define IDC_GRIDCLR                     1535
#define IDC_CHKAREABOXS                 1541
#define IDC_BKCLR                       1542
#define IDC_TOPRECT                     1543
#define IDC_SPPLTXSIZE                  1544
#define IDC_XSIZE                       1545
#define IDC_SPPLTYSIZE                  1551
#define IDC_FRCLR                       1552
#define IDC_YSIZE                       1553
#define IDC_CHKSTOPCHK                  1554
#define IDC_LINECLR                     1555
#define IDC_XCOUNT                      1561
#define IDC_EDNORISIRO                  1562
#define IDC_CURVCLR                     1563
#define IDC_YCOUNT                      1564
#define ID_DLGRESET                     1565
#define IDC_SUBLCLR                     1571
#define IDC_SPXSIZE                     1572
#define ID_DLGSET                       1573
#define IDC_EDNUMX                      1574
#define IDC_SLCTCLR                     1575
#define IDC_SPYSIZE                     1581
#define IDC_AREACLR                     1582
#define IDC_STSTRGSIZE                  1583
#define IDC_SPXCOUNT                    1584
#define IDC_SPYCOUNT                    1585
#define IDC_SCALCLR                     1591
#define IDC_CNTRCLR                     1592
#define IDC_ASSTCLR                     1593
#define IDC_STUNITX                     1594
#define IDC_IMAGECLR                    1595
#define IDC_STTITLEX                    1611
#define IDC_ATNCLR                      1612
#define IDC_CBSTYLE                     1613
#define IDC_LSLCTCLR                    1614
#define IDC_EDDOTSIZE                   1615
#define IDC_BTNDEFSET                   1621
#define IDC_NOSLCTCLR                   1622
#define IDC_CKMAXLEGAL                  1623
#define IDC_BEZECLR                     1624
#define IDC_BTN_BIG                     1625
#define IDC_KMNLIST                     1631
#define IDC_EDNAME                      1632
#define IDC_EDFULLNAME                  1633
#define IDC_SPSTEP                      1634
#define IDC_SET                         1635
#define IDC_LSTFILE                     1641
#define IDC_CMBGYOUSYA                  1642
#define IDC_CMBKOUJI                    1643
#define IDC_LSTSLCTFILE                 1644
#define IDC_STPATH                      1645
#define IDC_LSTSLCTDIR                  1651
#define IDC_STFILEIMG                   1652
#define IDC_EDCOMENT1                   1653
#define IDC_EDCOMENT2                   1654
#define IDC_EDCOMENT3                   1655
#define IDC_STIMG                       1661
#define IDC_RBTN_KADO                   1662
#define IDC_RBTN_KCUT                   1663
#define IDC_RBTN_ROUND                  1664
#define IDC_ED_OUTLINEMM                1665
#define IDC_EDTRNSLIMIT                 1671
#define IDC_CHKITRIC                    1672
#define IDC_CHKBOLD                     1673
#define IDC_CMBDATA                     1674
#define IDC_PRTCTL                      1675
#define IDC_CMBFILE                     1681
#define IDC_EDDEEPCUT                   1682
#define IDC_EDAREADOT                   1683
#define IDC_EDPOINTDOT                  1684
#define IDC_STCLR                       1685
#define IDC_LSTWAKUNAME                 1691
#define IDC_LSTSTRG1                    1692
#define IDC_LSTSTRG2                    1693
#define IDC_LSTITEM                     1694
#define IDC_CMBROUND                    1695
#define IDC_BTNLOAD                     1711
#define IDC_EDCODE                      1712
#define IDC_CMBKAKUSU                   1713
#define IDC_LSTIMG                      1714
#define IDC_CMBBUSYU                    1715
#define IDC_BTNSAVE                     1721
#define IDC_LSTCODE                     1722
#define IDC_CMBHANTEN                   1723
#define IDC_BTNSPACEKIND                1724
#define IDC_CMBFILD                     1725
#define IDC_STFILD                      1731
#define IDC_CMBFLATPAR                  1732
#define IDC_CMBSPACEMM                  1733
#define IDC_CMBODERKIND                 1734
#define IDC_CMBKANAPAR                  1735
#define IDC_CHKYOKOGUMI                 1741
#define IDC_EDR                         1742
#define IDC_SPR                         1743
#define IDC_EDSRAG                      1744
#define IDC_SPSRAG                      1745
#define IDC_EDERAG                      1751
#define IDC_SPERAG                      1752
#define IDC_EDPCID                      1753
#define IDC_EDSETKEY                    1754
#define IDC_STMSG                       1755
#define IDC_STMSG2                      1761
#define IDC_EDSIZEX                     1762
#define IDC_EDSIZEY                     1763
#define IDC_EDINTEXT                    1764
#define IDC_CHK_SHADOW                  1765
#define IDC_EDTOPSPACE                  1771
#define IDC_EDBOTTOMSPACE               1772
#define IDC_EDLEFSPACE                  1773
#define IDC_EDRIGHTSPACE                1774
#define IDC_EDSRCFOLDER                 1781
#define IDC_BTNSRCFOLDER                1782
#define IDC_STSRCXSIZE                  1783
#define IDC_STSRCYSIZE                  1784
#define IDC_EDDSTFOLDER                 1785
#define IDC_BTNDSTFOLDER                1791
#define IDC_EDDSTXSIZE                  1792
#define IDC_SPNDSTXSIZE                 1793
#define IDC_EDDSTYSIZE                  1794
#define IDC_SPNDSTYSIZE                 1795
#define IDC_EDSRCXSIZE                  1796
#define IDC_SPNSRCXSIZE                 1797
#define IDC_EDSRCYSIZE                  1798
#define IDC_SPNSRCYSIZE                 1799
#define IDC_LSTNAME                     1811
#define IDC_RDTABLE                     1812
#define IDC_RDQUERY                     1813
#define IDC_COMBOBOXEX1                 1814
#define IDC_CMBMAILADRS                 1820
#define IDC_EDSUBJECT                   1821
#define IDC_CMBFTPFOLDER                1822
#define IDC_EDFILENAME                  1823
#define IDC_CHKTONNBO                   1824
#define IDC_EDMEMOBACKPATH              1825
#define IDC_BTNMEMOBACKPATH             1826
#define IDC_EDMEMOPHOTOPATH             1827
#define IDC_BTNMEMOPHOTOPATH            1828
#define IDC_EDMEMOTEMPPATH              1829
#define IDC_BTNMEMOTEMPPATH             1830
#define IDC_PROGRESSBAR                 1831
#define IDC_REC_DEL                     1840
#define IDC_REC_UP                      1841
#define IDC_REC_DOWN                    1842
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_MOJI_LOAD                    32770
#define ID_MOJI_SAVE                    32771
#define ID_POINT_MOVE                   32772
#define ID_POINT_ADD                    32773
#define ID_POINT_DELETE                 32774
#define ID_LINE_MOVE                    32775
#define ID_LINE_CUTJOIN                 32776
#define ID_LINE_LINEING                 32777
#define ID_LINE_CURVE                   32778
#define ID_LINE_CUT                     32779
#define ID_LINE_JOIN                    32780
#define ID_FIGU_BOXS                    32781
#define ID_FIGU_CRCL                    32782
#define ID_FIGU_FREE                    32783
#define ID_TRNS_SIZE                    32784
#define ID_SIZE_FREE                    32785
#define ID_TRNS_ROUND                   32786
#define ID_ROUND_FREE                   32787
#define ID_TRNS_MIRR                    32788
#define ID_MIRROR_FREE                  32789
#define ID_TRNS_SLOP                    32790
#define ID_SLOP_FREE                    32791
#define ID_BMP_SCAN                     32792
#define ID_BMP_TRACE                    32793
#define ID_BMP_BMPING                   32794
#define ID_SYS_ENVSET                   32795
#define ID_EDIT_DELETE                  32796
#define ID_VIEW_PREVIEW                 32797
#define ID_FILE_ENVSET                  32798
#define ID_TOOL_LINE                    32799
#define ID_ZOOM_IN                      32800
#define ID_SLCT_AREA                    32801
#define ID_TOOL_POINT                   32802
#define ID_SLCT_ALL                     32803
#define ID_SLCT_CHNG                    32804
#define ID_ZOOM_ALL                     32805
#define ID_POINT_DEL                    32806
#define ID_MAIN_EDIT                    32807
#define ID_MAIN_ZOOM                    32808
#define ID_MAIN_SLCT                    32809
#define ID_OBJ_FIGU                     32810
#define ID_LINE_CURVEING                32811
#define ID_SCAN_SLCT                    32812
#define ID_SCAN_INPUT                   32813
#define ID_TOOL_TRACE                   32814
#define ID_TOOL_TRNS                    32815
#define ID_OBJ_STRG                     32816
#define ID_TOOL_SPCL                    32817
#define ID_MOJI_SVDEL                   32818
#define ID_MAIN_CRDNT                   32819
#define ID_FIGU_POINT                   32820
#define ID_FIGU_CNTR                    32821
#define ID_STRG_FONT                    32822
#define ID_STRG_TATEYOKO                32823
#define ID_STRG_MOJISIZE                32824
#define ID_STRG_MOJIFLATPAR             32825
#define ID_STRG_SPACEKIND               32826
#define ID_STRG_MOJISPACE               32827
#define ID_STRG_STRGSPACE               32828
#define ID_STRG_STRGSIZE                32829
#define ID_WAKU_TATEYOKO                32830
#define ID_WAKU_STARTKIND               32831
#define ID_WAKU_CONERKIND               32832
#define ID_FIGU_LINE                    32834
#define ID_MAIN_FILE                    32835
#define ID_MAIN_TOOL                    32836
#define ID_OBJ_WAKU                     32837
#define ID_OBJ_MSUR                     32839
#define ID_MAIN_ATR                     32840
#define ID_MAIN_SUB                     32841
#define ID_ATR_CLR                      32842
#define ID_FILE_PLOTER                  32843
#define ID_FILE_PLTMOVE                 32844
#define ID_FILE_ADDLOAD                 32845
#define ID_FILE_ADDSAVE                 32846
#define ID_FILE_CLRPRINT                32847
#define ID_STRG_EDIT                    32848
#define ID_STRG_ORDER                   32849
#define ID_STRG_ROUND                   32850
#define ID_STRG_SLOP                    32851
#define ID_STRG_BOXSIN                  32852
#define ID_STRG_PROP                    32853
#define ID_MOJI_DEL                     32854
#define ID_MOJI_INSEART                 32855
#define ID_MOJI_MOVE                    32856
#define ID_MOJI_PLGNING                 32857
#define ID_MOJI_ROUND                   32858
#define ID_MOJI_SIZE                    32859
#define ID_MOJI_SPACE                   32860
#define ID_FIGU_SIZEBOXS                32861
#define ID_FIGU_SIZECRCL                32862
#define ID_SLCT_OBJ                     32863
#define ID_MOVE_RLTV                    32864
#define ID_MOVE_COOD                    32865
#define ID_COPY_RLTV                    32866
#define ID_COPY_COOD                    32867
#define ID_COPY_PICH                    32868
#define ID_ZOOM_OUT                     32869
#define ID_POINT_SLOPLEGAL              32870
#define ID_LINE_HALFARC                 32871
#define ID_LINE_CRCL                    32872
#define ID_MIRROR_CNTR                  32873
#define ID_ROUND_2POINT                 32874
#define ID_ROUND_RAG                    32875
#define ID_SIZE_2POINT                  32876
#define ID_SIZE_TIME                    32877
#define ID_SIZE_X                       32878
#define ID_SIZE_Y                       32879
#define ID_SIZE_XY                      32880
#define ID_SLOP_RAG                     32881
#define ID_TRNS_ARC                     32882
#define ID_TRNS_BOXS                    32883
#define ID_SPCL_SHADOW                  32884
#define ID_SPCL_STRGSTRCT               32885
#define ID_SPCL_OMITOUTLINE             32886
#define ID_BMP_ROUND                    32887
#define ID_MSUR_XCREATE                 32888
#define ID_MSUR_YCREATE                 32889
#define ID_MSUR_ATRSET                  32890
#define ID_FILE_DOTEDIT                 32891
#define ID_GRUP_SET                     32892
#define ID_GRUP_RESET                   32893
#define ID_LIST_SET                     32894
#define ID_LIST_RESET                   32895
#define ID_CLR_SET                      32896
#define ID_SORT_HEAD                    32897
#define ID_SORT_TAIL                    32898
#define ID_SORT_NEXT                    32899
#define ID_SORT_PREV                    32900
#define ID_CLR_GRADATION                32901
#define ID_CLR_SEET_SET                 32902
#define ID_CLR_SOLID                    32903
#define ID_OBJ_BMP                      32904
#define ID_CLR_LINE                     32905
#define ID_ATR_CONER_KIND               32906
#define ID_TOOL_INPORT                  32907
#define ID_TOOL_EXPORT                  32908
#define ID_WAKU_GRUP                    32909
#define ID_WAKU_PAPER                   32910
#define ID_WAKU_CREATE                  32911
#define ID_WAKU_INPUT                   32912
#define ID_WAKU_SAVE                    32913
#define ID_WAKU_LOAD                    32914
#define ID_WAKU_EDIT                    32915
#define ID_WAKU_DELETE                  32916
#define ID_WAKU_LINEUP                  32917
#define ID_WAKU_SORT                    32918
#define ID_KAMON_LOAD                   32920
#define ID_SUB_GRID                     32921
#define ID_SUB_WAKU                     32922
#define ID_SUB_WAKUDEL                  32923
#define ID_SUB_ANYWAKU                  32924
#define ID_WAKU_CNTRKIND                32925
#define ID_FILE_OLE_EXIT                32926
#define ID_STRG_INPUT                   32927
#define ID_POINT_DIV                    32928
#define ID_POINT_LEGAL                  32929
#define ID_SPCL_BITMAPING               32930
#define ID_SPCL_PARALLEL                32931
#define ID_SPCL_PREPEND                 32932
#define ID_VIEW_IMAGE                   32933
#define ID_VIEW_BMP                     32934
#define ID_VIEW_GRID                    32935
#define ID_VIEW_REDISP                  32936
#define ID_HELP_MAIN                    32937
#define ID_KAMON_OLD_LOAD               32938
#define ID_ESKAMON_LOAD                 32939
#define ID_KAMON_OLD_SAVE               32940
#define ID_ESKAMON_SAVE                 32941
#define ID_BMP_SAVE                     32942
#define ID_BMP_LOAD                     32943
#define ID_BMP_TRNS                     32944
#define ID_SUB_GRID_ONOFF               32945
#define ID_OBJ_KAMON                    32948
#define ID_FILE_ADDENVLOAD              32949
#define ID_SPCL_MARGE                   32950
#define ID_CRDNT_TOP                    32951
#define ID_CRDNT_VCENTER                32952
#define ID_CRDNT_BOTTOM                 32953
#define ID_CRDNT_LEF                    32954
#define ID_CRDNT_LEFT                   32955
#define ID_CRDNT_HCENTER                32956
#define ID_CRDNT_RIGHT                  32957
#define ID_MOVE_HCENTER                 32958
#define ID_MOVE_VCENTER                 32959
#define ID_MOVE_HVCENTER                32960
#define ID_SIZE_HSAME                   32961
#define ID_SIZE_VSAME                   32962
#define ID_SIZE_HVSAME                  32963
#define ID_SPACE_HEQUAL                 32964
#define ID_SPACE_VEQUAL                 32965
#define ID_WAKU_BTNDSPWAKU              32966
#define ID_WAKU_BTNSETWAKU              32967
#define ID_PART_LOAD                    32967
#define ID_PART_SAVE                    32968
#define ID_POINT_CHNGATR                33111
#define ID_POINT_XLEGAL                 33112
#define ID_LINE_DEL                     33113
#define ID_LINE_BEZE                    33114
#define ID_LINE_ARC                     33115
#define ID_LINE_CONERARC                33121
#define ID_LINE_CONERSET                33122
#define ID_SPCL_OUTLINE                 33123
#define ID_EDIT_MOVE                    33124
#define ID_EDIT_MVCOPY                  33125
#define ID_POINT_YLEGAL                 33131
#define ID_POINT_PICUP                  33132
#define ID_POINT_ANYMOVE                33133
#define ID_POINT_ANYDEL                 33134
#define ID_POINT_2POINT                 33135
#define ID_SLOP_RL                      33141
#define ID_SLOP_UD                      33142
#define ID_FILE_ADDDEL                  33143
#define ID_PROTECT_KEYSET               33144
#define ID_CDNT_LINEUP                  33145
#define ID_TTTEXTINPUT                  33151
#define ID_CRDNT_SORT                   33152
#define ID_JOIN_AND                     33153
#define ID_JOIN_OR                      33154
#define ID_JOIN_NOT                     33155
#define ID_FILE_EPSOUT                  33161
#define ID_VIEW_WAKUBAR1                33162
#define ID_VIEW_WAKUBAR2                33163
#define ID_VIEW_WAKUBAR3                33164
#define ID_VIEW_WAKUBAR4                33165
#define ID_VIEW_WAKUSIDE                33171
#define ID_VIEW_LEFTSIDEBAR             33172
#define ID_VIEW_CLRTOOLBAR              33173
#define ID_MAIN_MENTE                   33174
#define ID_MAIN_DBEDT                   33175
#define ID_VIEW_EDITTOOLBAR             33181
#define ID_VIEW_CLRBAR                  33182
#define ID_BMP_SLCTDEL                  33183
#define ID_BMP_ALLDEL                   33184
#define ID_FILE_SLCTPRINT               33185
#define ID_FILE_CENTERKIND              33191
#define ID_FILE_SAVEPAPER               33192
#define ID_FILE_SETSPACE                33193
#define ID_WAKU_APPLY                   33194
#define ID_FILE_CRCTLOAD                33195
#define ID_FILE_CRCTSAVE                33211
#define ID_FILE_CRCTDEL                 33212
#define ID_DBEDT_LOAD                   33213
#define ID_DBEDT_DELETE                 33214
#define ID_WAKU_INSORT                  33215
#define ID_WAKU_CHANGE                  33221
#define ID_MOJI_FITING                  33222
#define ID_WAKU_PAPERDEL                33223
#define ID_CLR_BACKSET                  33224
#define ID_CLR_BACKRESET                33225
#define ID_BMP_JPGSAVE                  33231
#define ID_MENTE_CPTR_FOLDER            33232
#define ID_MENTE_CPTR_FILE              33233
#define ID_WAKU_PAPERADD                33234
#define ID_FIGU_PLGN                    33235
#define ID_FILE_EPSSEND                 33251
#define ID_FILE_MPRNSEND                33252
#define ID_FILE_PRNSEND                 34000
#define ID_FILE_MLTPRNFTP               34001
#define ID_FILE_EMLTPRNFTP              34002
#define ID_BMP_BKLOAD                   34003
#define ID_BMP_BKRESET                  34004
#define ID_BMP_CLIP                     34005
#define ID_MOJI_FONTCHANGE              34007
#define ID_FILE_MEMOENVSET              34009
#define ID_MEMO_WAKU_LOAD               34010
#define ID_MEMO_CALLPROG                34011
#define ID_MEMO_ENVSET                  34012
#define ID_MENTE_WAKU_BACKUP            34013
#define ID_WAKU_INSEKIJI                34014
#define ID_INDICATOR_TEXT1              59143
#define ID_INDICATOR_TEXT2              59144
#define ID_INDICATOR_TEXT3              59145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        425
#define _APS_NEXT_COMMAND_VALUE         34015
#define _APS_NEXT_CONTROL_VALUE         1841
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
